all:
	gcc fig5_4.c error.c -o fig5_4
	gcc fig5_5.c error.c -o fig5_5
	gcc fig5_5_unbuffered.c error.c -o fig5_5_unbuffered
	gcc fig5_5_line.c error.c -o fig5_5_line
	gcc fig5_5_fully.c error.c -o fig5_5_fully
